### ISSUE TITLE
Add package to Melpa

### ISSUE THREAD

**Issue by Simplify** [flycheck/flycheck-popup-tip#1]
@cpitclaudel, I'll like to bring this package in Melpa. `flycheck-pos-tip` doesn't work for me, I'm using Emacs mostly from TTY. Does it make sense to place to place it under Flycheck org? For me is the same, I'll support it anyway.

**Comment by cpitclaudel** [comment]
Absolutely. It's very welcome under the Flycheck org.

**Comment by Simplify** [comment]
@cpitclaudel Package is moved to Flycheck Github org

I added tests, ChangeLog, TravisCI en Coveralls.io integration. Only missing thing is CLA signing when somebody makes PR. Can you add that? I lost access to settings tab after moving repo to Flycheck Github organization and can't do it myself. Or maybe I can same way as I did with TravisCI and Coveralls, but have no idea how and where.

There is also [PR for adding package to Melpa](https://github.com/melpa/melpa/pull/4753). I'll update README with Melpa installation instructions and add a tag for Melpa stable. 

Please let me know if you want any changes.

**Comment by cpitclaudel** [comment]
Looks great, sorry for the delay.  I made you admin to this repo — is it enough to add the CLA signing?

**Comment by Simplify** [comment]
Hi @cpitclaudel, sorry for delay. 

I added CLA signing, it works. Only minor "problem" is that gist text for license signing for both flycheck repo and this repo is located in Sebastians account. Not sure is that a problem or not in long run.

**Comment by Simplify** [comment]
Finally in Melpa.
