### ISSUE TITLE
using as fallback in tty, when emacs daemon started graphically

### ISSUE THREAD

**Issue by unhammer** [flycheck/flycheck-popup-tip#5]
I sometimes open `emacsclient -nw` after starting emacs daemon with the GUI, in which case the tip about `(if (display-graphic-p)…` doesn't help, since it's only evaluated on daemon startup. This however seems to work:
```
  (setq flycheck-pos-tip-display-errors-tty-function #'flycheck-popup-tip-show-popup)
  (flycheck-pos-tip-mode)
```

**Comment by Simplify** [comment]
@unhammer Thanks for this info. Readme is updated to reflect it :)
